# Generated by Django 5.0.7 on 2024-08-20 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpp', '0004_rename_programmeduration_programme_programmeduration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('studentname', models.TextField(max_length=70)),
                ('studenthobby', models.TextField(max_length=50, null=True)),
                ('studentcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpp.programme')),
            ],
        ),
    ]
