# Generated by Django 5.0.7 on 2024-09-18 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpp', '0005_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studentcode',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
