# Generated by Django 5.1.1 on 2024-10-02 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpp', '0007_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('studentname', models.TextField(max_length=225)),
                ('studentemail', models.CharField(max_length=225)),
                ('studentage', models.PositiveSmallIntegerField(default=0)),
                ('studentmentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpp.mentor')),
            ],
        ),
    ]
