# Generated by Django 5.0.7 on 2024-08-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectcode', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('subjectname', models.TextField(max_length=50)),
                ('subjectcredithour', models.IntegerField(null=True)),
            ],
        ),
    ]
