# Generated by Django 5.0.7 on 2024-08-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpp', '0002_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='Programmeduration',
            field=models.IntegerField(default=3),
        ),
    ]
